[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "gift evil together autumn seven initial cash idle mutual pilot engine wisdom busy funny search loan can plug feed review disorder friend midnight alter"
